### PR TITLE
Add discord interactive

### PR DESCRIPTION
**Pull request by Initialize-A-Baguette**
I have an idea that send discord message when this tool detected that ran out of bait. This help user can check when bait is ran out to return with their PC

### CODE REVIEW

**Comment by mdnpascual** [comment]
This is a neat Idea. I haven't looked at discord's implementation and only read your code. I'm assuming you want to call `BuildOutOfBaitNotification()` when you ran out of bait.

The tool doesn't specifically know that it has ran out of bait. But you can check if the status is stuck from `FishingState.ResetStart` and hasn't progressed to `case FishingState.Fishing`. So you can do something like this:
1) On `FishngThread.Start` initialize the DateTime for the start of fishing
2) On the `case FishingState.ResetStart:`, create a 3 minute timer. Here's an example
```NoMoreBaitDelay = new DispatcherTimer(DispatcherPriority.Send, dis);
                        NoMoreBaitDelay.Interval = new TimeSpan(0, 0, 3, 0, 0);
                        NoMoreBaitDelay.Tick += (o, e) =>
                        {
                            BuildOutOfBaitNotification(dateTimeFromStep1);
                            NoMoreBaitDelay.Stop();
                        };
                        NoMoreBaitDelay.Start();
```
3) Call `.Stop()` of this new timer inside this if statement
```case FishingState.Fishing:
                        if (!fishStaminaDetected && playerStaminaDetected && PlayerStamina_lagCompensationDone)
                        {
                            ...
```

**Comment by Initialize-A-Baguette** [comment]
I'm not sure that this work or not cuz I can't compile due to lack of project WindowInput

**Comment by Miyakura** [comment]
> I'm not sure that this work or not cuz I can't compile due to lack of project WindowInput

https://github.com/mdnpascual/inputsimulator

**Comment by mdnpascual** [comment]
I see you updated the fishtingThread and iAppSettings. @Initialize-A-Baguette 

I'll code review and test this on the weekend. Meanwhile, can I request you to also update the Readme.md on how to modify `settings.json` to use this feature and the steps they needed to make it work. Like for example how to get their `DiscordUserId` or `DiscordHookUrl` 

You can also have your own `Readme.md` under the `Addon/DiscordInteractive/` if you think it's going to be a lot longer to document how to use it.

I'll try to add these 2 settings on the other PR I'm doing where I'm providing GUI to those advanced settings

**Comment by Initialize-A-Baguette** [comment]
Hi @mdnpascual,
I updated `README.md` if you want to review it, you can visit [here](https://github.com/Initialize-A-Baguette/ToF-Fishing-Bot/tree/Discord_Interactive#discord-notification)

**Review by mdnpascual — CHANGES_REQUESTED** [review]
I found 2 Issues

First: It will spam you with a ton notification until you manually stop click stop fishing.

image

Second, if you manually stop fishing, wait for 3 minutes then start fishing again. It will send the notification. Notice the Start at and End at is the same

image

I think using the `DispatchTimer` method I mentioned here https://github.com/mdnpascual/ToF-Fishing-Bot/pull/12#issuecomment-1509331469 will fix these 2 issues.

Let me know if you aren't able to compile your build to be able to test it yourself.

**Comment by Initialize-A-Baguette** [comment]
I fixed it but I cannot tested it now

**Review by mdnpascual — APPROVED** [review]
Thanks for the updates. The 2 bugs mentioned previously is not happening anymore

**Pull request merged**
